### PR TITLE
Add links to Confidential Storage spec on secure data storage wg page

### PR DESCRIPTION
**Pull request by gobengo**
Motivation:
* today i went to the secure data storage wg site to get a link to this spec but I was surprised that only the dwn spec was linked to, and the confidential storage spec was not even a hyperlink.

### CODE REVIEW

**Comment by paulgrehan** [comment]
Hi @gobengo - correct, there are a couple of imminent PRs to update the respective repository (Confidential Storage will be archived and split into EDV and DWN) and website WG links to reflect. 

An overview of the PRs :

- EDV Spec to have a name change (from Confidential Storage to EDV Spec)
- Confidential Storage repository to be archived with update to README to reflect the split between EDV and DWN (renamed Identity Hub)
- DIF website WG page updated to reflect

Does this address your concern ?

**Comment by gobengo** [comment]
@paulgrehan 

> correct, there are a couple of imminent PRs to update the respective repository (Confidential Storage will be archived and split into EDV and DWN) and website WG links to reflect.

It's been a month. How imminent?

Perhaps this PR is an improvement over the status quo without really preventing those other changes too

**Comment by paulgrehan** [comment]
> @paulgrehan
> 
> > correct, there are a couple of imminent PRs to update the respective repository (Confidential Storage will be archived and split into EDV and DWN) and website WG links to reflect.
> 
> It's been a month. How imminent?
> 
> Perhaps this PR is an improvement over the status quo without really preventing those other changes too

@gobengo - apologies, yes, this would be an improvement, even better would be to reference it by the Spec which is now Encrypted Data Vaults v0.1 (as opposed to Confidential Storage) - that would save the last step. - Thanks !

**Comment by gobengo** [comment]
@paulgrehan Thanks for the guidance. I made a commit to update to edv terminology and edv-spec links/repo. wdyt?

**Comment by paulgrehan** [comment]
Thanks @gobengo looks good, by way of governance -> @dmitrizagidulin, @DRK3 are you happy this reflects the changes in hte specs ?

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Review by paulgrehan — COMMENTED** [review]
Updated approved by SDS Chair ✅

**Pull request merged**
